export const planetData = [
  {
    name: "Mercury",
    size: 0.4,
    distance: 4,
    color: "#A9A9A9",
    orbitSpeed: 10,
    rotationSpeed: 58.6,
    hasRings: false,
    realDiameter: 4_879,
    realDistance: 57.9,
    orbitalPeriod: "88 days",
    dayLength: "59 Earth days",
    description: "The smallest and innermost planet in the Solar System.",
    funFact: "Despite being close to the Sun, Mercury has ice in its polar craters.",
  },
  {
    name: "Venus",
    size: 0.6,
    distance: 6,
    color: "#E6E6FA",
    orbitSpeed: 15,
    rotationSpeed: 243,
    hasRings: false,
    realDiameter: 12_104,
    realDistance: 108.2,
    orbitalPeriod: "225 days",
    dayLength: "243 Earth days",
    description: "The second planet from the Sun and Earth's closest planetary neighbor.",
    funFact: "Venus rotates in the opposite direction to most planets.",
  },
  {
    name: "Earth",
    size: 0.6,
    distance: 8,
    color: "#6B93D6",
    orbitSpeed: 20,
    rotationSpeed: 1,
    hasRings: false,
    realDiameter: 12_756,
    realDistance: 149.6,
    orbitalPeriod: "365.25 days",
    dayLength: "24 hours",
    description: "Our home planet and the only known place with life in the universe.",
    funFact: "Earth is the only planet not named after a god or goddess.",
  },
  {
    name: "Mars",
    size: 0.5,
    distance: 10,
    color: "#E27B58",
    orbitSpeed: 30,
    rotationSpeed: 1.03,
    hasRings: false,
    realDiameter: 6_792,
    realDistance: 227.9,
    orbitalPeriod: "687 days",
    dayLength: "24.6 hours",
    description: "The fourth planet from the Sun, often called the Red Planet.",
    funFact: "Mars has the largest dust storms in the solar system, lasting for months.",
  },
  {
    name: "Jupiter",
    size: 1.2,
    distance: 14,
    color: "#E0CFBB",
    orbitSpeed: 60,
    rotationSpeed: 0.41,
    hasRings: false,
    realDiameter: 142_984,
    realDistance: 778.6,
    orbitalPeriod: "11.9 years",
    dayLength: "9.9 hours",
    description: "The largest planet in our Solar System, a gas giant with a Great Red Spot.",
    funFact: "Jupiter's Great Red Spot is a storm that has been raging for at least 400 years.",
  },
  {
    name: "Saturn",
    size: 1.0,
    distance: 18,
    color: "#F4F4E2",
    orbitSpeed: 90,
    rotationSpeed: 0.45,
    hasRings: true,
    ringColor: "#E1C9A8",
    ringTilt: 0.4, // Slight tilt to the rings
    realDiameter: 120_536,
    realDistance: 1_433.5,
    orbitalPeriod: "29.5 years",
    dayLength: "10.7 hours",
    description: "The sixth planet from the Sun, famous for its spectacular ring system.",
    funFact: "Saturn's rings are made mostly of ice chunks, with some rocky debris and dust.",
  },
  {
    name: "Uranus",
    size: 0.8,
    distance: 22,
    color: "#D1E7E7",
    orbitSpeed: 120,
    rotationSpeed: 0.72,
    hasRings: true,
    ringColor: "#A5A5A5",
    ringTilt: 0.1, // Slight tilt to the rings
    realDiameter: 51_118,
    realDistance: 2_872.5,
    orbitalPeriod: "84 years",
    dayLength: "17.2 hours",
    description: "The seventh planet from the Sun, an ice giant that rotates on its side.",
    funFact: "Uranus rotates on its side, with its axis pointing nearly toward the Sun.",
  },
  {
    name: "Neptune",
    size: 0.8,
    distance: 26,
    color: "#5B5DDF",
    orbitSpeed: 150,
    rotationSpeed: 0.67,
    hasRings: false,
    realDiameter: 49_528,
    realDistance: 4_495.1,
    orbitalPeriod: "165 years",
    dayLength: "16.1 hours",
    description: "The eighth and most distant planet from the Sun, a stormy ice giant.",
    funFact: "Neptune has the strongest winds in the Solar System, reaching 2,100 km/h.",
  },
]
